# Generated by Django 3.0.11 on 2021-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField()),
                ('shippername', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
